### ISSUE TITLE
ConcepPath using PLIP

### ISSUE THREAD

**Issue by bryanwong17** [HKU-MedAI/ConcepPath#1]
Hi, thanks for the great work! I wonder if PLIP is applied to the ConcepPath, does it mean the code inside related to the `PromptLearner` and `TextEncoder` must be changed? As what I notice, `clip_model = CLIPModel.from_pretrained("vinid/plip").to(device)` has different model structure let say with `clip_model, _, preprocess = open_clip.create_model_and_transforms('hf-hub:wisdomik/QuiltNet-B-32')`. Thanks!

**Comment by mateguo0** [comment]
Hi, thank you very much for your interest in our work. Yes, as you mentioned, when using the PLIP model, it is necessary to adjust the code for the PromptLearner and TextEncoder according to its unique layer structure.

**Comment by bryanwong17** [comment]
Got it, thanks!
